### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yumeyuniko** [yumeyuniko/furima-28113#9]
|入力内容 | 備考 | 
| :--- | :---: | 
| フリマアプリのURL | https://furima-28113.herokuapp.com/ | 
| Basic認証のIDとパスワード| ID:admin  / password:2222 | 
| 出品者用のメールアドレスとパスワード| ✉️:sample@msn.com   🔑:111aaa | 
| 購入者用のメールアドレスとパスワード| ✉️:sample1@msn.com   🔑:111aaa | 
|購入用カードの番号・期限・セキュリティコード| カード番号 :4242424242424242 |  
|セキュリティコード|CVC: 123|  
|有効期限|登録時より未来|

**Comment by tomonari94** [comment]
小形さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by yumeyuniko** [comment]
お世話になりました
ありがとうございます🎉
